### ISSUE TITLE
Repeating events (2-n) not in subject_event_crf_status

### ISSUE THREAD

**Issue by rbmobius** [lindsay-stevens/openclinica_sqldatamart#1]
Hi Lindsay,

I am looking in "subject_event_crf_status" and cannot find a record for the 2x+ repeating events.
Should they be there?

Thanks,

Richard

**Comment by lindsay-stevens** [comment]
Thanks, yes these records should be there, but they aren't. It looks like its because dm.subject_event_crf_status has:

``` sql
SELECT DISTINCT ON (cd.study_name, cd.subject_id, cd.event_oid, cd.crf_version_oid)
```

Which should be:

``` sql
SELECT DISTINCT ON (cd.study_name, cd.subject_id, cd.event_oid, cd.event_repeat, cd.crf_version_oid)
```

I didn't notice probably because we don't use repeating events. 

Fixed in commit b42ccf1ec576caf6d1f09b6451cbdf415bfa8e94 which has been merged in to the master branch as version 2015.003

Thanks again
